name: blaze_router
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/hawkkiller/blaze_router

environment:
  sdk: ">=2.18.0 <=2.18.0"
  flutter: ">=3.3.1 <=3.3.1"

dependencies:
  collection: 1.16.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path: 1.8.2
  path_to_regexp: 0.4.0
  purple_lints: 0.3.0
  radix_tree: 1.2.0

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
