name: blaze_router
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/hawkkiller/blaze_router

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: 1.16.0
  flutter:
    sdk: flutter
  path: 1.8.1
  path_to_regexp: ^0.4.0
  purple_lints: 0.3.0
  radix_tree: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  test: 1.21.1

flutter: